### ISSUE TITLE
update package on npm

### ISSUE THREAD

**Issue by savelichalex** [johanneslumpe/react-native-fs#111]
Looks like need update package on npm. When I'm trying to use .downloadFile with options as js object I have this error `JSON value '{...}' of type NSDictionary cannot be converted to NSString`. However when I'm switching to old function style with just arguments, this work fine

**Comment by cjdell** [comment]
@savelichalex A release might be in order. Have added quite a few new features since the last release. There are a few other PR's I need to sort, but don't want to add too much at once :-)

What do you think @johanneslumpe? I have tested the new features so I am reasonably confident in releasing.

**Comment by johanneslumpe** [comment]
@cjdell Did we merge breaking changes? If so, we'll have to release 2.0, else 1.5

**Comment by cjdell** [comment]
@johanneslumpe I have made `downloadFile` so that it still supports the old parameter format. I've changed the docs so people only see the new format

**Comment by cjdell** [comment]
@johanneslumpe Added a deprecated warning for this

**Comment by johanneslumpe** [comment]
@cjdell ok cool 1.5 it is!

**Comment by johanneslumpe** [comment]
Just published `1.5.0` to npm.
