### ISSUE TITLE
Support for unicode

### ISSUE THREAD

**Issue by tiojoca** [johanneslumpe/react-native-fs#13]
Some unicode characters and strings are not correctly read or written. This can be fixed by surrounding the decode with `decodeURIComponent` and `escape` when reading and doing the reverse on encoding when writing, as described in https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/btoa#Unicode_Strings

**Comment by johanneslumpe** [comment]
Feel free to submit a pr :)

**Comment by cjdell** [comment]
Unicode (UTF8) is now supported as the default encoding type for strings.
