### ISSUE TITLE
PDF does not scroll and responds very slow.

### ISSUE THREAD

**Issue by bhumit1709** [johanneslumpe/react-native-fs#143]
I am facing this issue where PDF renders only first page and does not scroll on iOS (yet to test on android) moreover, while zooming pdf responds very slow and zooming is very far from smooth. The example bundled with this github project also has the same issues

**Comment by johanneslumpe** [comment]
@bhumit1709 Did you by any chance post on the wrong repo?

**Comment by bhumit1709** [comment]
Yes , I am extremely sorry for this .

**Comment by johanneslumpe** [comment]
No worries :)
