### ISSUE TITLE
progress divider doesn't work correctly. 

### ISSUE THREAD

**Issue by windmemory** [johanneslumpe/react-native-fs#148]
I like this package, and I am trying to build something using the fs here. But I found something not working here. 

It seems like no matter what value I give to the progressDivider when I use the download API, it is still performs as it was 0. 
I really need to throttle this callback, otherwise the performance of the app is awful. 

Any idea why this happens?

**Comment by CesarLanderos** [comment]
hahaha, funny i just stumbled on this too, it happens on android and its because there is no release with this feature yet, i figured it out by looking on the tags and branches, i am thinking in installing the latest commit on my app but i do not know how stable it is :fearful:

**Comment by cjdell** [comment]
This will be fixed in V2.
