### ISSUE TITLE
Doesnot it support append file method?

### ISSUE THREAD

**Issue by susylPearl** [johanneslumpe/react-native-fs#156]

**Comment by johanneslumpe** [comment]
No, the library does not support this as of now. Feel free to submit a PR for this functionality for iOS and Android though.

**Comment by cjdell** [comment]
@susylPearl @johanneslumpe We do have `appendFile` in V2, see README.md

**Comment by johanneslumpe** [comment]
@cjdell my oh my, how could I miss that :D ok great, closing!
