### ISSUE TITLE
JWT authentication error:Forbidden

### ISSUE THREAD

**Issue by gauravbhusare** [johanneslumpe/react-native-fs#157]
I am using RNFS with PDFView to display PDF. I am trying to download a pdf file from website which have JWT authentication, request is going but there is authentication issue, it is giving 403 response. I am doing it as follows,

          var pdfPath=this.pdfPath;
        alert(pdfDownloadURL)
        var DownloadFileOptions={
             fromUrl: pdfDownloadURL,          // URL to download file from
              toFile: pdfPath,           // Local filesystem path to save the file to
 
              headers: {'Authorization' : DEMO_TOKEN}    // An object of headers to be passed to the server
  
       }
       RNFS.downloadFile(DownloadFileOptions).then(res => {
            alert(res)
            this.setState({isPdfDownload: true});
        }).catch(err => {
            alert(err);
            this.props.navigator.pop
        });`
Please help me finding solution. thanks in advance.

**Comment by gauravbhusare** [comment]
@johanneslumpe  please go through it.

**Comment by johanneslumpe** [comment]
@gauravbhusare have you checked which headers are transmitted to your server? Is the issue that no headers arrive or is it something else?

**Comment by gauravbhusare** [comment]
no header is getting transmitted to my server. I printed req. header then it is showing

{"user-agent":"Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)","host":"192.168.100.64:8000","connection":"Keep-Alive","accept-encoding" :"gzip"}

**Comment by cjdell** [comment]
@gauravbhusare Looks like you're using an older version of the lib. I know this because `downloadFile` now returns an object rather than the promise directly. Try updating the lib and remember to add `.promise.then` instead of `.then` due to the breaking changes in V2.

**Comment by gauravbhusare** [comment]
@cjdell hey thanks headers are getting passed now but while displaying the file it is showing that no such file or directory, open 'data/user/0/com.example/files/test.pdf'. My code is now as follows.

    RNFS.downloadFile(DownloadFileOptions).promise.then(res => {
            
            this.setState({isPdfDownload: true});
            
        }).catch(err => {
            alert("Error is:-"+err);
            this.props.navigator.pop
        });
       
the same code was showing file before using .promise.then and before upgrading version. I am using version  2.0.1-rc.2

**Comment by gauravbhusare** [comment]
now it is transmitting headers but it is not getting authenticated. now my req.header looks as follows
     {"authorization":"value","user-agent":"Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)","host":"192.168.100.64:8000","connection":
"Keep-Alive","accept-encoding":"gzip"}

**Comment by gauravbhusare** [comment]
@johanneslumpe @cjdell Will you please tell me how to send user with req object? With fetch method it automatically sent to server but with RNFS there is no user object in request.

**Comment by johanneslumpe** [comment]
@gauravbhusare If the headers are sent as expected, why are you assuming that it's an issue with the library? What do you mean by "user" object? What kind of user would `fetch` send automatically?

**Comment by gauravbhusare** [comment]
My problem get solved. Actually I need to change the code at backend. Thanks for help..
