### ISSUE TITLE
Could not find file in device

### ISSUE THREAD

**Issue by YjyJeff** [johanneslumpe/react-native-fs#163]
I use RNFS.writeFile('/data/data/com.awesomeproject/files/test.txt','test','utf-8') method to create the 'text.txt' file. I can read the the file content by RNFS.readFile('/data/data/com.awesomeproject/files/test.txt','utf-8'),but I can not find the 'test.txt' file in my device . Where is the file in device?

**Comment by 1050509299** [comment]
Do u find the file in device?
