### ISSUE TITLE
method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by fgrs** [johanneslumpe/react-native-fs#165]
I can't get it installed and i'm confused whether to update both MainActivity.java and MainApplication.java or just MainApplication.java, Im running react-native 0.31.0 and getting following error:

MainApplication.java:42: error: method does not override or implement a method from a supertype

after adding this in MainApplication.java:

`import com.rnfs.RNFSPackage;`

```
@Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      new MainReactPackage(), // <---- add comma
      new RNFSPackage() // <---------- add package
    );
  }
```

**Comment by fgrs** [comment]
solved by adding this line only to MainApplication.java

'new RNFSPackage()'

**Comment by bfarrgaynor** [comment]
Even with this adjustment, I'm getting the same error in RN53. 
```
:react-native-fs:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/projects/cpScratch/131-002/myProject/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSPackage.java:20: error: method does not override or implement a method from a supertype
  @Override
  ^
Note: /projects/cpScratch/131-002/myProject/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by Lube** [comment]
Just delete that line (the override annotation), in RN 53 CreateJSModules is not required / implemented in android.

**Comment by katktv** [comment]
This honestly really needs to be clarified in the README, it caused too much pain to me for no good reason whatsoever.
