### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by fgrs** [johanneslumpe/react-native-fs#166]
I'm trying to get base64 out of the resized image but running readFile gives me this error:

`Error: ENOENT: no such file or directory, open 'file:/data/data/com.app/cache/1472039430399.JPEG'(…)`

any idea why?

**Comment by johanneslumpe** [comment]
@fgrs are you sure that the URI is supposed to only start with `file:` instead of `file://`? Can you access the same URI using native Java code?

**Comment by fgrs** [comment]
`RNFS.readFile(resizedImageUri.replace('file:/', ''), 'base64').then((base64) => {`

did the trick, looks like returned path is wrong should start with **data/data/...**

**Comment by johanneslumpe** [comment]
@fgrs ok, so then this is not an issue with RNFS I assume :) Feel free to reopen if you still think that we can do something here.

**Comment by sergiocloud** [comment]
@johanneslumpe  I have the same issue. I use .replace('file:/', '') but when file has spaces like: "Introdution to Java.pdf" the error appears again. Any solution?

**Comment by joaovpmamede** [comment]
@sergiocloud try to replace it like:
`path.replace(/%20/g, '\ ')`

Works for me.
