### ISSUE TITLE
Have working Android implementation, need to integrate somehow...

### ISSUE THREAD

**Issue by cjdell** [johanneslumpe/react-native-fs#17]
I've been working on an Android port as I really need cross platform support. Documentation on creating reusable modules supporting Android is still weak but I have succeeded in creating a demo project from scratch which demonstrates a sample app working on both platforms:
https://github.com/cjdell/react-native-fs

Here is Java implementation itself:
https://github.com/cjdell/react-native-fs/blob/master/android/app/src/main/java/com/rnfs/RNFSManager.java

I've tried to mirror your existing API closely but the current FS abstraction may need to change a little, i.e. Android doesn't have the concept of a documents directory as such.

Would be good to merge this with your module somehow, though not quite ready for pull request yet. I'm putting this out there in case there are others who want this. Please let me know how I can help out, it would be good to have Android support in this module :-)

Thanks

**Comment by johanneslumpe** [comment]
@cjdell awesome! I'm totally not a Java guy, but seeing you putting all the effort into this is great! Would love to have cross platform support in the lib. Not sure what the equivalent for document directories etc would be - is there nothing like that on android at all?

**Comment by cjdell** [comment]
Created a pull request, I've compromised a little and support only the Documents directory for now. Demo project here: https://github.com/cjdell/react-native-fs-test

Would you trust me with access to the repository? :-)

**Comment by johanneslumpe** [comment]
@cjdell check your permissions ;) I currently cannot check out the demo project, am a bit busy, but I trust that you will do a good job!

**Comment by cjdell** [comment]
@johanneslumpe Awesome, thanks :-) It's official now, just merged my pull request. This may end up becoming the de facto FS module for React Native :-)

**Comment by johanneslumpe** [comment]
Let's see about that :)

**Comment by johanneslumpe** [comment]
@cjdell have you tested it thoroughly? If so we could cut a new release

**Comment by cjdell** [comment]
@johanneslumpe Have tested it with demo app so I'm reasonably confident.

Not sure how one goes about automated tests in ReactNative but this would increase my confidence. I'm currently building an app using this module so if I find problems I will be fixing them in the days to come :-)

Also why is version of NPM module package.json higher than version in GitHub?

**Comment by johanneslumpe** [comment]
Because I forgot to push the commit which bumps the version to github :/

**Comment by johanneslumpe** [comment]
@cjdell do you want to test this in your app a bit more first before we push out a new version?

**Comment by cjdell** [comment]
@johanneslumpe Sure, as I say I'm building an app at the moment so it should be a good test. Also thinking of adding a mkdir and maybe a downloadFile

**Comment by johanneslumpe** [comment]
Let's close this as it has been integrated :)
