### ISSUE TITLE
securing data

### ISSUE THREAD

**Issue by hybrisCole** [johanneslumpe/react-native-fs#170]
Is there a way where I can like have a file only be accessed for my app? I'm planning to save some images and videos but I would not like having anyone using them in other place but the app

**Comment by CesarLanderos** [comment]
thats more ios/android related you have to store ir in a folder where only your app has access, i dont have the exact info but i am sure that you can find it on the corresponding documentation, also, in the readme file, there is a section that explains this module folder  constants.

**Comment by johanneslumpe** [comment]
This question rather belongs on stackoverflow :)
