### ISSUE TITLE
downloadFile doesn't support for data scheme

### ISSUE THREAD

**Issue by nodegin** [johanneslumpe/react-native-fs#171]
Hello everyone,

how can I download file or writing to disk from `data` scheme  like `data:image/png;base64,...`?

I have googled already but it looks like this library is missing an ability to doing that.

**Comment by CesarLanderos** [comment]
as fas as i know, to write on disk with a base64 string like the example you posted, you need to strip the string so you only have the actual base54 string, like, the `data:image/png;` which its not part of the real base64, those are like headers for the browser so it knows its rendering a base64 image

**Comment by nodegin** [comment]
@CesarLanderos It works, thank you for the solution but it would be great if support downloading data URIs.
