### ISSUE TITLE
DocumentDirectoryPath: Cannot find path/file in IOS10

### ISSUE THREAD

**Issue by larryranches** [johanneslumpe/react-native-fs#179]
I recently upgraded my ios device version to IOS 10 and am noticing a breaking error when trying to retrieve/view file (in my case a video) that was stored using DocumentDirectoryPath.

This code has been and IS WORKING perfect with IOS9 but seems to not find the file where it's being stored to in ios10. 

Was there any changed in IOS10 to break this code on where the file system is stored? or any info on this? Any help would be much appreciated. Thanks!

I'm also using RN 0.33 and react-native-fs 1.5.1

**Code to set the path:**

`const path = RNFS.DocumentDirectoryPath + '/MyApp/capturedvideo.MOV'`

**Error on ios 10:**

ExceptionsManager.js:78 Error processing request body: Error Domain=NSCocoaErrorDomain Code=260 "The file “capturedvideo.MOV” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/CAA95020-0F76-48C7-8BC3-CCE1FB969071/Documents/MyApp/capturedvideo.MOV, NSUnderlyingError=0x1742499f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by larryranches** [comment]
Okay after reading into the directory and analyzing,  it seems tobe changing my file name from 'capturedvideo.mov' to '49618610439__71CD4B12-6D0C-4D6E-A8DD-23C779F34CB3.MOV' 

Full path below:

"/var/mobile/Containers/Data/Application/7F9636B8-4C33-406B-AC3B-15C7E2DFC019/Documents/Stardust/**49618610439__71CD4B12-6D0C-4D6E-A8DD-23C779F34CB3**.MOV"

any ideas?

**Comment by harshsrivastavaglobussoft** [comment]
@larryranches  did you find any solution for this issue ?
