### ISSUE TITLE
downloadFile example for v2.x

### ISSUE THREAD

**Issue by davidperrenoud** [johanneslumpe/react-native-fs#186]
This example worked in v1.5.1, but seems to have broken since v2.0.0:

```javascript
RNFS.downloadFile(url, path).then(res => {
  this.setState({ downloaded: true });
});
```

Could you add a working example of `downloadFile` usage in the README?

**Comment by kiliwalk** [comment]
```
RNFS.downloadFile(url, path).promise.then(res => {
  this.setState({ downloaded: true });
});
```
The document [here](https://github.com/johanneslumpe/react-native-fs#downloadfileoptions-downloadfileoptions--jobid-number-promise-promisedownloadresult-) is clear

**Comment by palaniraja** [comment]
As per the document, 

```
RNFS.downloadFile(url, path).promise.then(res => {
  this.setState({ downloaded: true });
});
```

seems to be invalid, the following one works as of today.

```
RNFS.downloadFile({fromUrl:url, toFile: path}).promise.then(res => {
  this.setState({ downloaded: true });
});

```

Thank you @kiliwalk

**Comment by ArwaLh** [comment]
Thank you so much.Now it's working !!

**Comment by apoorv-1310** [comment]
it is working and downloading file but i dont see that file in the photo app

**Comment by Keftaa** [comment]
When you trigger this function, what's the default behavior per OS? 

I'm expecting that when the user taps the download button, it will open a file browser to let the user choose the download location. So in the future the user can open the file from his phone from outside the app. 

What will it actually do on iOS and on Android?

**Comment by azizijunaid** [comment]
ES6 style
const downloadFile = async () =>{
    try{
        const data = await RNFS.downloadFile(url, path).promise;
        if(data){
              this.setState({ downloaded: true });
        }
        

    }catch(error){
        console.log('error', error)
    }
}

**Comment by mouhsnimohamed** [comment]
> it is working and downloading file but i dont see that file in the photo app 

I have the same problem, how did you resolved it?
