### ISSUE TITLE
readdir should take absolute path for uniformity with other methods

### ISSUE THREAD

**Issue by cjdell** [johanneslumpe/react-native-fs#19]
@johanneslumpe Do you think it is reasonable to drop the 2nd argument and make `readDir` take an absolute path? It's not an issue that can't be worked around but I think new comers might think this is a little odd?

I'm raising this now so we don't get design quirks set in stone when we reach version 1.0 :-)

**Comment by johanneslumpe** [comment]
@cjdell Yeah I think that would be fine. For that we then definitely have to bump to 1.0 before shipping. But that's cool with me :)

**Comment by cjdell** [comment]
@johanneslumpe Awesome, it that case might also make `readFile` and `writeFile` more uniform and more Node like (basically add encoding param). :-)

**Comment by cjdell** [comment]
@johanneslumpe I'm very happy with the API now, it is now more Node like. I think a feature freeze might be in order.

By the way I appreciate you giving me the freedom to make these changes. I really hope this becomes a popular library. :-)

**Comment by johanneslumpe** [comment]
@cjdell I don't think the features of the lib ever changed since I published it :D

**Comment by cjdell** [comment]
@johanneslumpe Well I added a `downloadFile` to bypass JS pipeline because `writeFile` is slow. Other than that it has mostly been interface changes and of course Android support.

Is it easy enough to publish the module? Do you want to commit to a 1.0 release?

**Comment by johanneslumpe** [comment]
@cjdell Oh I didn't notice that method before! Cool - did you test it thoroughly? Also in terms of connection errors etc?

Publishing this is easy yeah :) We can do a 1.0 release.

**Comment by cjdell** [comment]
@johanneslumpe Made some minor fixes today. I've noticed in Android that downloadFile blocks the UI on large files but not in iOS. Will need to have some fun with threads. Will have to be tomorrows job. :-)

**Comment by johanneslumpe** [comment]
@cjdell oh that's a bummer :( I hope you can figure that out though! :+1:

**Comment by johanneslumpe** [comment]
@cjdell Is everything working as expected now? I saw you changed the `downloadFile` method to an `AsyncTask`

**Comment by cjdell** [comment]
@johanneslumpe Yeah it's working much better now. Nearly ready to publish my Android app. You might as well publish to NPM :-)

**Comment by johanneslumpe** [comment]
@cjdell https://www.npmjs.com/package/react-native-fs :)

**Comment by cjdell** [comment]
@johanneslumpe Awesome!
