### ISSUE TITLE
stat for a non-existent file gives: RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSError)

### ISSUE THREAD

**Issue by neilsarkar** [johanneslumpe/react-native-fs#191]
## Steps to reproduce

First, turn on remote debugging. Then:

```js
import RNFS, {DocumentDirectoryPath} from 'react-native-fs';

//...
RNFS.stat(DocumentDirectoryPath+'/notHere.jpg').catch((err) => {
  console.warn(err);
})
```

From the stack trace, it appears that the error is coming from react native attempting to serialize the native `NSError` provided by `NSFileManager` and send it over the websocket to the remote debugger.

## Workaround

Turn off remote debugging.

**Comment by wafisher** [comment]
How'd you find the stack trace? All I see in the stack are react files not the call that triggered this.

**Comment by neilsarkar** [comment]
sorry, I meant the objective C stack trace. I added a breakpoint where the error was (in react native code attempting to stringify an `NSError` into json and traced it back. Don't know enough yet about react internals to know what it is expecting instead of an `NSError` in the callback. Probably some sort of wrapped error.

**Comment by wafisher** [comment]
Hmm I can't even get that much. That shows up in Xcode?

**Comment by neilsarkar** [comment]
Indeed. I found the file using cmd+shift+o in xcode and added a breakpoint at line 82 like this:

<img width="1061" alt="ecra_inteiro_21_10_16_12_25_am" src="https://cloud.githubusercontent.com/assets/83109/19581468/0ded7d74-9725-11e6-84b6-8c15dcb1041a.png">

you can then use the xcode debugging utility to step through the threads to find the call that dispatched the unwrapped `NSError`

**Comment by neilsarkar** [comment]
This seems to be an underlying error in react native. I've opened this issue there https://github.com/facebook/react-native/issues/10506

**Comment by fungilation** [comment]
I'm hitting a similar error:
```
RCTJSONStringify() encountered the following error: Invalid type in JSON write (NSURL)
```

With `NSURL` in brackets instead.

**Comment by fungilation** [comment]
Traced this issue to triggering on every app launch, only with use of https://github.com/CRAlpha/react-native-wkwebview

**Comment by lakshmantgld** [comment]
@fungilation I am getting the same error at RN 0.42. Any updates on this issue ? How did you resolve it ?

**Comment by coffeeexistence** [comment]
@fungilation If the JS you pass to `evaluateJavascript` on wkwebview causes an error within the webview, it will cause this issue to appear.
