### ISSUE TITLE
Append to file

### ISSUE THREAD

**Issue by johanneslumpe** [johanneslumpe/react-native-fs#2]
It might be useful to allow appending to a file

**Comment by KishPatel1996** [comment]
Was this closed because it was added?

**Comment by johanneslumpe** [comment]
@KishPatel1996 No. This has been some time ago haha but I had no concrete use case for this so I closed it. We don't have appending functionality right now afaik.

**Comment by KishPatel1996** [comment]
Awesome, thanks for the heads up.
