### ISSUE TITLE
What do I need to use in my project.

### ISSUE THREAD

**Issue by wootwoot1234** [johanneslumpe/react-native-fs#20]
I'm trying to use this on iOS.  I installed 'react-native-fs' then added the 'libsqlite3.tbd' library and then installed 'bluebird' but I'm still getting "Error: undefined is not an object (evaluating 'RNFSManager.readDir')".  What can I do to fix this error?

**Comment by johanneslumpe** [comment]
`libsqlite3.tbd` has nothing to do with this project. Neither should you have to install bluebird on your own if you do not use it. You will have to add this project's library after you installed it.

Please refer to https://github.com/johanneslumpe/react-native-fs#usage and post back if those instructions do not solve your issue.

**Comment by wootwoot1234** [comment]
Sorry, my bad.  I made a mistake on my end, the component is working well now.  Thanks!

**Comment by timojaask** [comment]
I faced the same problem and found this issue. Unfortunately the person who posted this question did not provide his solution to the problem, but after reading through instructions again, I noticed that I missed the `react-native link react-native-fs` step.

Then I started wondering how could I have missed that and realised that I used the instructions from npmjs.org, which I guess are outdated and do not include this step:
https://www.npmjs.com/package/react-native-fs
