### ISSUE TITLE
Component installation failed

### ISSUE THREAD

**Issue by shanuks** [johanneslumpe/react-native-fs#209]
I am trying to install this component with below command:
npm install react-native-fs --save

It is returning below errors:

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-fs" "--save"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.35.0 wants react@~15.3.1
npm ERR! peerinvalid Peer react-native-statusbar-alert@0.0.2 wants react@15.0.2
npm ERR! peerinvalid Peer react-test-renderer@15.3.2 wants react@^15.3.2

Please help!

**Comment by johanneslumpe** [comment]
Your issue is not related to this package. We have a peer dependency on react with `^15.2.1`, which allows `15.3.2`.

Your installed `react-native` version does not allow for the `react` version you want to install. And `react-native-statusbar-alert` is failling too.
