### ISSUE TITLE
Cannot save file on MainBundlePath iOS!!!

### ISSUE THREAD

**Issue by edolfuchs** [johanneslumpe/react-native-fs#210]
I'm downloading a file and saving on MainBundlePath. The simulator works fine, but in the real device I can not save the file.

The error below appears

{"line":"65","column":"216","sourceURL":"file:\/\/\/var\/containers\/Bundle\/Application\/1D00DBD7-A146-4692-AC21-6DD71B93A157\/embracotools.app\/main.jsbundle","framesToPop":"1","code":"EDOWNLOADER-1100","domain":"Downloader","userInfo":{"NSLocalizedDescription":"Failed to create target file at path: \/var\/containers\/Bundle\/Application\/1D00DBD7-A146-4692-AC21-6DD71B93A157\/embracotools.app\/compressores.sqlite.zip"},"nativeStackIOS":["0 embracotools 0x001448ed embracotools + 841965","1 embracotools 0x001130a5 embracotools + 639141","2 embracotools 0x001a3245 embracotools + 1229381","3 embracotools 0x001a4b79 embracotools + 1235833","4 embracotools 0x001a1c1f embracotools + 1223711","5 CoreFoundation 0x241804c4 + 68","6 CoreFoundation 0x240a687d + 292","7 CoreFoundation 0x240aa2f7 + 50","8 embracotools 0x00113447 embracotools + 640071","9 embracotools 0x0013438f embracotools + 775055","10 embracotools 0x00133e19 embracotools + 773657","11 libdispatch.dylib 0x23ce9823 + 10","12 libdispatch.dylib 0x23cf6423 + 1758","13 libdispatch.dylib 0x23cf5a61 + 284","14 libdispatch.dylib 0x23cf85e9 + 1560","15 libdispatch.dylib 0x23cf7fcd + 96","16 libsystem_pthread.dylib 0x23eadb29 _pthread_wqthread + 1024","17 libsystem_pthread.dylib 0x23ead718 start_wqthread + 8"]}

On android works...

I'm doing this:

Does not work:
RNFS.downloadFile({ fromUrl: url, toFile: RNFS.MainBundlePath/compressores.sqlite.zip,...})...

It works:
RNFS.downloadFile({ fromUrl: url, toFile: RNFS.DocumentDirectoryPath/compressores.sqlite.zip,...})...

Using:
react: "15.3.2",
react-native: "^0.35.0",
react-native-fs: "^2.0.1-rc.2"

**Comment by edolfuchs** [comment]
****

**Comment by johanneslumpe** [comment]
This is not an issue with the library and expected. The main bundle is immutable. You have to use the document directory as you already discovered.
