### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by chadwilken** [johanneslumpe/react-native-fs#213]
Is this repo still under maintenance? I notice that there was some commits recently but that the last tagged 2.x.x hasn't been updated since August.

**Comment by johanneslumpe** [comment]
I currently do not have any spare time to devote for this project :/

**Comment by grabbou** [comment]
I am on the last version and I am likely to continue keeping it `working` as long as few of my apps are running.

**Comment by grabbou** [comment]
Anyway, if you read this issue in the future and would like help with further development - please ping me on twitter so I can see your notification :)
