### ISSUE TITLE
Question. How to see the result of console.log

### ISSUE THREAD

**Issue by ejabu** [johanneslumpe/react-native-fs#221]
> // require the module
> var RNFS = require('react-native-fs');
> 
> // get a list of files and directories in the main bundle
> RNFS.readDir(RNFS.MainBundlePath) // On Android, use "RNFS.DocumentDirectoryPath" (MainBundlePath is not defined)
>   .then((result) => {
>     console.log('GOT RESULT', result);
> 
>     // stat the first file
>     return Promise.all([RNFS.stat(result[0].path), result[0].path]);
>   })
>   .then((statResult) => {
>     if (statResult[0].isFile()) {
>       // if we have a file, read it
>       return RNFS.readFile(statResult[1], 'utf8');
>     }
> 
>     return 'no file';
>   })
>   .then((contents) => {
>     // log the file contents
>     console.log(contents);
>   })
>   .catch((err) => {
>     console.log(err.message, err.code);
>   });

It is written like this in readme.md.

I wonder, there is a console.log, how do you see the result? 

I am new to react-native, I always compile it to Android before observe the result..

best regards

**Comment by johanneslumpe** [comment]
You have to look at your debugging console of your IDE to see the logs.

**Comment by ejabu** [comment]
I am new to this.

I googled it, and found many new term such as  : Deco, Nuclide, Exponent and Android Studio.

Is this what you mean? Which one do you think it will suit best as I used to develop using only Atom

best regards

**Comment by johanneslumpe** [comment]
@ejabu that's probably a question for [stackoverflow.com](http://stackoverflow.com/). But you could just get started with Android Studio. It's all about personal preference though.

**Comment by ejabu** [comment]
Yes Indeed, but I can't resist myself to ask directly to you

sorry then.

Thank you for your kindness
