### ISSUE TITLE
Update to react-native 0.40

### ISSUE THREAD

**Issue by adrienbataille** [johanneslumpe/react-native-fs#234]
Hi,

React Native 0.40 is out since one week and my project no more working due to react-native-fs.
There is 4 PR to fix that (#223 #229 #232 #233). Can someone anywhere make a review please and accept one of the 4 PR?!

Thanks

**Comment by johanneslumpe** [comment]
Please take a look at https://github.com/johanneslumpe/react-native-fs/issues/228

**Comment by adrienbataille** [comment]
Thanks @johanneslumpe. I'll take a look at https://github.com/wkh237/react-native-fetch-blob and see how can I replace react-native-fs in my project by react-native-fetch-blob.

**Comment by benvium** [comment]
@adrienbataille If you do want to stick this this, our company will be using this repo on react native 0.40 pretty soon - so I'll take a look at the PRs (#229 looks most promising at a glance) and if it works I'll merge.

**Comment by adrienbataille** [comment]
@benvium The PR #229 is promising, but you should update devDependencies for react to >=15.4.2 and react-native to >=0.40

**Comment by benvium** [comment]
@adrienbataille Will do - thank you

**Comment by benvium** [comment]
@adrienbataille Ok, done. I've added a new [pre-release version](https://github.com/johanneslumpe/react-native-fs/releases/tag/v2.1.0.rc.1)

 @johanneslumpe If you're happy, can you push the release to npm?

**Comment by johanneslumpe** [comment]
@benvium I've just published the new version to npm. `react-native-fs@2.1.0-rc.1`
