### ISSUE TITLE
Download percentage

### ISSUE THREAD

**Issue by crysfel** [johanneslumpe/react-native-fs#24]
Is there a way to get the download percentage? 

    RNFS.downloadFile('http://test.com/download.zip',RNFS.DocumentDirectoryPath + '/download.zip')

I would like to show a loader bar or show the user how long will it take to finish the download. I haven't seen anything in the docs.

Regards

**Comment by cjdell** [comment]
@crysfel No way to do this as yet but it is planned. Download progress is something I will be needing for an upcoming project.

Out of interest, what do you plan to do with the zip file after it is downloaded? Will you be wanting to extract it? Reading large amounts of data as base64 is very slow. I can see there being a need for an `unzip` method. :-)

**Comment by crysfel** [comment]
Awesome! I will keep an aye on this project.

I'm planning to unzip it, I have some sounds and images that I will load into the app.

**Comment by johanneslumpe** [comment]
Closing this for now, feel free to re-open if you feel like it.

**Comment by cjdell** [comment]
@crysfel Just implemented a progress callback, have a look at the README for more info :-)
