### ISSUE TITLE
Change import paths for react-native 0.40

### ISSUE THREAD

**Issue by abec** [johanneslumpe/react-native-fs#241]
The import paths currently look like this:
```
#import <React/RCTLog.h>`
```

For react-native 0.39.x and newer it should look like this:
```
#import "RCTLog.h"
```

**Comment by alex-Z-** [comment]
Generally problem not only in repo, but also in React Native itself, as I can see in RCTBridge it still some links to React/*

**Comment by alfonsodev** [comment]
I would change the title of this issue to react-native `0.40` [it's the version where this is really a problem.](https://github.com/facebook/react-native/releases/tag/v0.40.0)

**Comment by alex-Z-** [comment]
Yeah, very true, as for myself I found solution to add this task to package and run after installing dependencies ( I really tied to 0.4 ) probably will be useful for someone 

`"compat": "[ ! -L node_modules/react-native/React/React ] && cd node_modules/react-native/React && find ./ -type l | xargs rm &&  ln -s Base React && ln -s Base/* ./$1"`

**Comment by abcd-ca** [comment]
[These are the needed fixes](https://github.com/mindoktor/react-native-fs/commit/7b53573bb24c979029a8a7b742af312c38693c0e), I tried adding them manually to my RN 0.40.0 project and it worked. l've requested the author create a pull request

**Comment by abec** [comment]
I updated the pull request with recommendations from https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.vh7nbtd26. Could some one review/commit this?

https://github.com/johanneslumpe/react-native-fs/pull/242

**Comment by jjhesk** [comment]
do we need to do cocoapod for RNFS for RN 0.41.2

???

**Comment by abec** [comment]
Thanks @benvium for merging.

@jjhesk not sure what you mean. It seems like the install instructions reference a local directory for cocoapods.

Closing this issue since it was addressed in #242
