### ISSUE TITLE
dataWithContentsOfURL Not Suggested for Downloading Files from Network

### ISSUE THREAD

**Issue by cancan101** [johanneslumpe/react-native-fs#25]
`downloadFile` [uses `dataWithContentsOfURL`](https://github.com/johanneslumpe/react-native-fs/blob/354a21857384c496730d130e748c5eed91da5d6f/RNFSManager.m#L148) which [per the Apple docs](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSData_Class/#//apple_ref/occ/clm/NSData/dataWithContentsOfURL:options:error:), is not ideal:
>Discussion
This method is ideal for converting data:// URLs to NSData objects, and can also be used for reading short files synchronously. If you need to read potentially large files, use inputStreamWithURL: to open a stream, then read the file a piece at a time.

>>IMPORTANT
Do not use this synchronous method to request network-based URLs. For network-based URLs, this method can block the current thread for tens of seconds on a slow network, resulting in a poor user experience, and in iOS, may cause your app to be terminated.

>>Instead, for non-file URLs, consider using the dataTaskWithURL:completionHandler: method of the NSURLSession class. See URL Session Programming Guide for details.

**Comment by johanneslumpe** [comment]
@cancan101 yeah that is an oversight, a sync method shouldn't have been used there.

/cc @cjdell

**Comment by cjdell** [comment]
@cancan101 @johanneslumpe Noted, I can change this. It's strange though that it didn't seem to block for me. Maybe because React Native runs its UI stuff on it's own threads?

**Comment by cancan101** [comment]
I think the `downloadFile` native method get's dispatched on a new thread.

**Comment by cjdell** [comment]
@cancan101 @johanneslumpe OK I've reimplemented this using `NSURLConnection`. I think the way React Native handles native calls was disguising the problem, however this needed to be done anyway to allow for another requested feature which was download progress, which is next on my todo list.
