### ISSUE TITLE
RNFSManager.RNFSFileTypeRegular is undefined

### ISSUE THREAD

**Issue by natashache** [johanneslumpe/react-native-fs#259]
Hi all,

I just downloaded this module. And when I tried to import it into my components, I was given the error "undefined is not an object (evaluating 'RNFSManager.RNFSFileTypeRegular')". I'm using React Native 0.40.0. Tried directly download the module from the current master on github, instead of using npm. Didn't work, either. Any idea why it's not working?

Natasha

![screenshot 2017-02-18 14 12 15](https://cloud.githubusercontent.com/assets/19754530/23096133/59958848-f5e4-11e6-81d3-b37ca7fcc914.png)

**Comment by hugihlynsson** [comment]
RNFS is a NativeModule so it seems like react-native-fs it's not linked to the project. Did you run `react-native link react-native-fs`? See: https://github.com/johanneslumpe/react-native-fs#usage-ios

**Comment by natashache** [comment]
@hugihlynsson Using react-native link didn't do it.  I linked it manually and it worked. Thanks!

**Comment by tkale1** [comment]
@natashache Can you please help me with how did you manually linked this module? I am stuck at the same error.

**Comment by natashache** [comment]
@tkale1 After doing react-native link, I followed the two steps for manual linking here https://facebook.github.io/react-native/docs/linking-libraries-ios.html. 

Also, I basically gave up on this module (because of other issues) and I'm using react-native-fetch-blob instead.

**Comment by itinance** [comment]
there shouldnt be any linking issues if one does this the right way.

react-native init x
cd x
yarn add react-native-fs
react-native link
... add some custom code
react-native run-ios

works.

**Comment by Dictory** [comment]
Don\`t forget `pod install`

**Comment by Hermanya** [comment]
On android, after linking, I had to manually add `new RNFSPackage()` to getPackages in MainApplication.java

**Comment by Kida007** [comment]
still auto linking doesnt work , manually it works like charm!

**Comment by smakosh** [comment]
manually linked it but still getting an issue which isn't really clear `CompileC ....`

**Comment by jarodsmk** [comment]
> On android, after linking, I had to manually add `new RNFSPackage()` to getPackages in MainApplication.java

I just ran `react-native link react-native-fs` which did automatically add it in to the `getPackages` function in `MainApplication.java`, but still get this error when building for Android only :/ really at a loss here

**Comment by smakosh** [comment]
This has been fixed for me, you most likely need to update your gradle version on your project

**Comment by quarryman** [comment]
Automatic linking doesnt work.
Manual linking doesnt work following all the steps.
Installing corresponding version of library with respect to your RN version as manual says doesnt help.

What other steps should one try to have this solved?

**Comment by smakosh** [comment]
go work in a farm

**Comment by Venipa** [comment]
This is currently happening on RN 0.60.5

**Comment by research506** [comment]
this is also happening for me. I am using Expo
