### ISSUE TITLE
Inconsistent Saving Implementation

### ISSUE THREAD

**Issue by cancan101** [johanneslumpe/react-native-fs#26]
There seem to be two different methods being used to save `NSData` and I am not sure why:
```objectivec
BOOL success = [[NSFileManager defaultManager] createFileAtPath:filepath contents:data attributes:attributes];

BOOL success = [urlData writeToFile:filepath atomically:YES];
```

**Comment by johanneslumpe** [comment]
@cancan101 Where did you see `BOOL success = [urlData writeToFile:filepath atomically:YES];` in the codebase?

**Comment by cjdell** [comment]
@johanneslumpe It's gone now, I rebuilt `downloadFile`. :-)

**Comment by johanneslumpe** [comment]
oh :D Ok cool, then we can close this :+1:
