### ISSUE TITLE
Ability to Save Binary Blob

### ISSUE THREAD

**Issue by cancan101** [johanneslumpe/react-native-fs#27]
It looks like the current writeFile method wants the data to be base64 encoded. If I want to save the contents of data obtained using the JS network interface: https://facebook.github.io/react-native/docs/network.html#content, is there some way to avoid the base64 encoding step?

**Comment by cjdell** [comment]
@cancan101 Not as far as I know. Unfortunately the bridge between JS and native code is always going to be slow and is the reason I introduced a (poorly) written `downloadFile`. This effectively means that all data heavy lifting operations will need to be pushed beneath the filesystem abstraction that this API provides. Another API method that I might need to implement soon is `unzip`. This will be way too slow to do outside of native.

**Comment by johanneslumpe** [comment]
@cancan101 The data has to be sent from JS to native, and that is done via a string. As @cjdell pointed out, this will be slow for any larger amount of data. The way around this is to employ native libraries which do downloads etc. for you and have their interface exposed in JS land.
