### ISSUE TITLE
Add Method to Check if File Exsits

### ISSUE THREAD

**Issue by cancan101** [johanneslumpe/react-native-fs#30]
Right now best I can see is to use `stat` and check error case.

**Comment by fov42550564** [comment]
+1

**Comment by cjdell** [comment]
@cancan101 @fov42550564 I will implement this feature shortly as it is a quick win.

**Comment by andreacab** [comment]
+1

**Comment by Mirodil** [comment]
+1

**Comment by sibeliusseraphini** [comment]
any workaround this?

**Comment by grabbou** [comment]
fs.readdir on the containing directory is the way to go ;)

**Comment by lu-ko** [comment]
+1

**Comment by corbt** [comment]
This was recently merged in https://github.com/johanneslumpe/react-native-fs/pull/48.

**Comment by cjdell** [comment]
@johanneslumpe Sorry for being inactive for a while. I merged in a pull request for this feature a couple of weeks ago. My test app shows this working so it might be worth doing another NPM release when you get a moment. Thanks

**Comment by johanneslumpe** [comment]
Published with `1.3.0`
