### ISSUE TITLE
Release a version for new download features

### ISSUE THREAD

**Issue by demiurga** [johanneslumpe/react-native-fs#32]
At this time, the version on npm is 1.0.0, without new download features. I'm tried use the github version but it seams build fail. Can you release a version with these cool new features?

**Comment by cjdell** [comment]
Only @johanneslumpe can do this at the moment, speaking of which, can I be added as a collaborator on NPM?

In the meantime @demiurga you can directly reference the GitHub repo in your package.json for the latest version.

**Comment by johanneslumpe** [comment]
@cjdell are we set for a 1.1? Is there anything left to test? @demiurga Your build failed with The current version on github?

@cjdell I'll check out how to do that on Npm :) But we should still have some kind of milestone set up and not wildly publish to npm :D

**Comment by demiurga** [comment]
@cjdell @johanneslumpe Sorry, that's my fail. The current version on GitHub works fine :)

**Comment by cjdell** [comment]
@johanneslumpe I think a version 1.1 release is in order. I'm unlikely to be adding any new stuff over the next few days. I might get some time over Christmas to add some requested features for a version 1.2...

**Comment by johanneslumpe** [comment]
@cjdell I will publish that now but I also added you on npm!

**Comment by johanneslumpe** [comment]
@demiurga published as `1.1.0`

**Comment by cjdell** [comment]
@johanneslumpe Sorry to reopen this but just noticed the readme on NPM is still the old one. Close this as soon as you've updated. Thanks

**Comment by cjdell** [comment]
@johanneslumpe Showing up now, closing the issue :-)
