### ISSUE TITLE
Remove photo

### ISSUE THREAD

**Issue by skeie** [johanneslumpe/react-native-fs#34]
Hi, 

I have this url `assets-library://asset/asset.JPG?id=F970CE98-0BB8-400B-B4C8-AF7A938CF775&ext=JPG` which I am trying to delete, which i get from [react-native-camera](https://github.com/lwansbrough/react-native-camera)

I tried to prefix it with both `LibraryDirectoryPath` and `DocumentDirectoryPath`, and without a prefix. The `catch` method is invoked and the `err.message` tells me that the file does not exist.

Any suggestion on how to use fs to delete the photo?

**Comment by johanneslumpe** [comment]
Hey, a little bit of research turned up that there is no ability on iOS < 8 to delete an image from the camera roll. According to https://developer.apple.com/library/ios/documentation/Photos/Reference/PHAssetChangeRequest_Class/index.html#//apple_ref/occ/clm/PHAssetChangeRequest/deleteAssets you can do this in newer iOS versions but you will need permission from the user to do so. I feel that this is a bit out of the scope of this library though.

/cc @cjdell

**Comment by skeie** [comment]
Ah, thanks @johanneslumpe!

**Comment by johanneslumpe** [comment]
You're welcome @skeie
