### ISSUE TITLE
Error: 'RCTRootView.h' file not found

### ISSUE THREAD

**Issue by wootwoot1234** [johanneslumpe/react-native-fs#36]
I'm getting an error:

     'RCTRootView.h' file not found

I'm using a fresh build of react native 0.17.

**Comment by wootwoot1234** [comment]
Never mind.  My bad.

**Comment by mahlon-gumbs** [comment]
@wootwoot1234 how did you resolve this? I've started seeing this issue again with react native 0.28.

**Comment by mahlon-gumbs** [comment]
I can get things to run if I remove AppDelegate.m and main.m from the "Compile Sources" of the IntegrationTests target. Wondering if that's the correct solution.

**Comment by wootwoot1234** [comment]
@mahlon-gumbs I'm forgetting what solved this issue for me but it was something I did wrong.  Maybe try building a new app with only react-native-fs and see if you still get the error.  My guess is you won't.  If you can't figure it out, I would recommend creating a new project, import your code and plugins and I'll bet the problem will go away.  When you do figure it out, post it the solution here for the next person.  That's what I should have done, sorry.

**Comment by mahlon-gumbs** [comment]
@wootwoot1234 no worries. Thanks for the info. I'll see if I find something better than the "Compile Sources" mod I mentioned above. Will report back if I do.
