### ISSUE TITLE
stopDownload() doesn't return a Promise

### ISSUE THREAD

**Issue by af** [johanneslumpe/react-native-fs#37]
The readme indicates that it should, but I'm not sure if that's a docs error. Every other call in the API returns a Promise, so I'm guessing that would be the intended behaviour.

**Comment by cjdell** [comment]
Good spot, this method is effectively synchronous so it doesn't return a promise. I've corrected the README to reflect this. Thanks

**Comment by af** [comment]
Makes sense, thanks!
