### ISSUE TITLE
Unlinking a video file but memory footprint for app does not change.

### ISSUE THREAD

**Issue by tomtang539** [johanneslumpe/react-native-fs#41]
I'm saving a video to a temporary local directory.  Once I'm done, I unlink the file which appears to succeed but the memory footprint of the app remains unchanged as if the file was not removed.

**Comment by johanneslumpe** [comment]
Have you tried running your app in the simulator and inspecting the local storage directory to see whether the file actually has been removed? Is this iOs or Android related?

**Comment by tomtang539** [comment]
I'm not able to test it on the simulator since I'm recording the videos via the device.  Instead, I'm testing it directly on my iPhone.  The 'FILE DELETED' message shows up but when I check on my phone's storage settings, the memory size hasn't decreased.  Is there something else I need to do to relinquish the memory from the OS's point of view?

**Comment by johanneslumpe** [comment]
Oh you are recording a video using the camera? Then your issue could be related to this:

https://github.com/johanneslumpe/react-native-fs/issues/34

Files in the asset library cannot be removed like a normal file.

**Comment by tomtang539** [comment]
Ah, interesting.  I'm using react-native-screcorder.  I'll check over there to see if there's a solution.  Thanks!
