### ISSUE TITLE
Does it possible to download files in android/app/src/main/res/raw ?

### ISSUE THREAD

**Issue by yellow066** [johanneslumpe/react-native-fs#55]
Hi.

I'm trying to do program which will download mp3 from internet, save it and play. But all players that I found use "raw" folder for playing. Do you have any advise, how I can work with this folder?

**Comment by johanneslumpe** [comment]
@yellow066 Sorry, I'm not really into Android. Have you tried to specify a path for `downloadFile`?

**Comment by johanneslumpe** [comment]
Closing as inactive.

**Comment by isener** [comment]
is there any solution on it? Now I'm faced that problem on android

**Comment by itinance** [comment]
i would guess that this folder is for readonly usage. Can someone confirm?

**Comment by isener** [comment]
Yeah possible, but event we can't read any file from res folder also

**Comment by itinance** [comment]
Have you tried this method [readFileAssets](https://github.com/itinance/react-native-fs#readfileassetsfilepathstring-encoding-string-promisestring)

**Comment by isener** [comment]
It only shows assets/ folder unfortunately.. I tried as a relative path `../res` doesn't work though. but found a pr which implements in raw folder as assets. if works, will be notify from here.
