### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by magrinj** [johanneslumpe/react-native-fs#57]
Hello,

I have an issue on this package, I follow the steps to add the package on Xcode but when I try to import or require RNFS I got a white screen.

**Comment by magrinj** [comment]
That's work if I run my app within Xcode but if I run `react-native run-ios`, I still got a white screen.
I don't really understand why.

**Comment by johanneslumpe** [comment]
@magrinj Without more information on your project setup this is hard to diagnose. If you set up a blank app with RNFS, do you get a white screen?

**Comment by johanneslumpe** [comment]
Closing as inactive.

**Comment by GeoffreyPlitt** [comment]
Saw this today. Happens at the moment we do RNFS.downloadFile(). Might be an uncaught error or something?

**Comment by hiteshagja** [comment]
Reading file from location and I am getting white screen. 
`async componentDidMount() {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
      )
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        RNFS.readFile(`${RNFS.ExternalStorageDirectoryPath}/Download/mitsui.csv`)
          .then((result) => {
            insertData(result).then((res) => {
              this.setState({
                loading: false
              })
            });
          }).catch((err) => {
            alert(err);
            this.setState({
              loading: false
            })
          })
      } else {
        this.setState({
          loading: false
        })
      }
    } catch (err) {
      console.warn(err)
      this.setState({
        loading: false
      })
    }
  }`

it is working fine If I remove readFile
