### ISSUE TITLE
[exception] fn must be a function

### ISSUE THREAD

**Issue by 9mm** [johanneslumpe/react-native-fs#65]
This doesn't happen when I use 1.2.0, but 1.3.0 does, any ideas?

![image](https://cloud.githubusercontent.com/assets/1386207/14179222/4e7ccf00-f72c-11e5-88d2-863f4b769e5f.png)

**Comment by johanneslumpe** [comment]
@9mm sorry I didn't have any time to investigate this. Does it still not work for you?

**Comment by 9mm** [comment]
It appears to work now :+1:

**Comment by magrinj** [comment]
@9mm How did you solved that issue ?

**Comment by 9mm** [comment]
I honestly dont remember :( I might have just upgraded it. I believe it was a bug in the dependency and when they fixed it it just started working (bluebird)

**Comment by vitalbone** [comment]
Going to put this here for the next poor sod that runs into this issue.

The fix for me was:

- Remove `react-native-fs@^1.4.0` from package.json
- Remove node_modules and clean npm cache
```
rm -rf node_modules
npm cache clean
```
- `npm i`

- Install `react-native-fs` separately (without caret)
```
npm i -S react-native-fs@1.4.0
```

Hope that helps 🙂
