### ISSUE TITLE
downloadFile does not follow redirects on Android

### ISSUE THREAD

**Issue by cancan101** [johanneslumpe/react-native-fs#71]
Right now downloadFile does not follow redirects on Android where it does on iOS.

**Comment by cancan101** [comment]
I added this hack to download and it "works" though it is a hack:
```java
      if(statusCode == 302) {
        String location = headers.get("Location").get(0);
        param.src = new URL(location);
        download(param, res);
        return;
      }
```

**Comment by cancan101** [comment]
In investigating further it looks looks like `HttpURLConnection` on [Android won't follow redirects from HTTP to HTTPS](http://developer.android.com/reference/java/net/HttpURLConnection.html):
>This implementation doesn't follow redirects from HTTPS to HTTP or vice versa.

whereas it seems the library on iOS does.

**Comment by johanneslumpe** [comment]
This should work as of version `1.5.0`.
