### ISSUE TITLE
Access to /tmp directory? 

### ISSUE THREAD

**Issue by andreacab** [johanneslumpe/react-native-fs#76]
Hi, 

Thanks for the great work! It's been very helpful so far. 

I was wondering if there is a way to access the /tmp directory?

Thanks,
Andrea

**Comment by johanneslumpe** [comment]
@andreacab you mean the temporary directory on iOS? (`NSTemporaryDirectory`)  That is not implemented at the moment but I'm sure it could be added. Do you know whether there is a temporary directory available on Android too?
