### ISSUE TITLE
need 'copy' function.

### ISSUE THREAD

**Issue by yulinho** [johanneslumpe/react-native-fs#81]
is possible to implement 'copy' function?

**Comment by yulinho** [comment]
why don't we add this simple function on it,is any  reason i don't know?

**Comment by johanneslumpe** [comment]
@yulinho you are welcome to send a PR for this.

**Comment by faceyspacey** [comment]
i would, but my objective C skills are lacking. was there any challenges that caused it to be left out?

**Comment by johanneslumpe** [comment]
@faceyspacey I didn't include it at the time because I just didn't think about it. Nowadays I just lack time.

**Comment by superandrew213** [comment]
Sent PR #127 for this. In the meantime you can just use my fork

**Comment by johanneslumpe** [comment]
Fixed with 6d129706572c8674977280839634a32b160d88eb
