### ISSUE TITLE
Switch to promises on native side

### ISSUE THREAD

**Issue by grabbou** [johanneslumpe/react-native-fs#87]
Instead of promisifying with Bluebird, I think we could just use native promise abstraction supported by the bridge. Happy to PR if that sounds like a good improvement!

**Comment by johanneslumpe** [comment]
@grabbou If it cleans up the code base, then by all means, why not. Are there performance drawbacks?

**Comment by grabbou** [comment]
Not that I am aware of. It's just a tiny wrapper on top of callbacks. I have few minutes now, going to give it a go.
