### ISSUE TITLE
Subscriptions are likely never removed

### ISSUE THREAD

**Issue by grabbou** [johanneslumpe/react-native-fs#90]
https://github.com/johanneslumpe/react-native-fs/blob/master/FS.common.js#L170

If both being and progress are registered, the latter will overwrite the former which causes the subscriptionAndroid.remove() to only clear the last assigned.

We should use an array instead. We should also stick to one emitter regardless of the platform (NativeAppEventEmitter), I am going to send a patch for that as well.

**Comment by johanneslumpe** [comment]
@grabbou sounds good to me. If `NativeAppEventEmitter` works for both iOS and Android, I'm all for just using that one.

Thanks for catching that bug, definitely not cool for those listeners to override each other and hog memory like that. Looking forward to the PR :)
