### ISSUE TITLE
npm install gives wrong version 1.3 instead of 1.4

### ISSUE THREAD

**Issue by itinance** [johanneslumpe/react-native-fs#98]
when running "npm install react-native-fs" the older version 1.3 will be installed. Also when applying a specific version with "@1.4.0"

Unfortunatly the 1.3 isn't compatible with Cocoapods 1.0.0 due to missing parameters in Podspec-file ("authors" and "summary"), which is already fixed in 1.4

This is what i get after the install-commands listed above:

![screen shot 2016-05-25 at 20 19 17](https://cloud.githubusercontent.com/assets/1758597/15551391/09c069f2-22b6-11e6-9184-2845feed2e39.png)

What goes wrong there with "npm install"?

$ npm -v
3.8.9
$ pod --version
1.0.0

**Comment by tristola** [comment]
Same situation here. Master has the changes needed for using cocoapods.

**Comment by johanneslumpe** [comment]
This should have been resolved with the latest version (1.5)
